Update setup.py
we cannot use statements as `import inferno.__version__` in the setup.py since this statment is going to evaluate `inferno.__init__`
This leads to many errors
```
    from inferno.version import __version__
  File "/home/thorsten/src/inferno/inferno/__init__.py", line 5, in <module>
    from . import extensions
  File "/home/thorsten/src/inferno/inferno/extensions/__init__.py", line 1, in <module>
    from . import containers
  File "/home/thorsten/src/inferno/inferno/extensions/containers/__init__.py", line 1, in <module>
    from .graph import *
  File "/home/thorsten/src/inferno/inferno/extensions/containers/graph.py", line 8, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
```